### ISSUE TITLE
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by jimoquinn** [iost-official/explorer#1]
What version of python do you recommend?  I receive the following error:

**gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.**

When running:

**npm install**

I'm happy to update the README's prerequisites section with python and the recommended version.

**Comment by jimoquinn** [comment]
FIxed long ago, so closing.

**Comment by patrickgdl** [comment]
`echo "export PYTHON=/usr/bin/python3" >> ~/.bashrc && source ~/.bashrc && npm install` didn't work but with python2.7 instead worked, thanks!

**Comment by vikasedulab** [comment]
i have still get issue while i am running this command
